### ISSUE TITLE
Missing wheel for macOS

### ISSUE THREAD

**Issue by ntoxeg** [cswinter/pyron#4]
The wheel for Python 3.10 for macOS is missing, making it impossible to install this and HyperSpace.

**Comment by cswinter** [comment]
There should be Python 3.10 wheels now with hyperstate==0.2.3, if you still run into issues let me know.

**Comment by cswinter** [comment]
Hmm ok nvmd there's still something funky happening with the publish action that prevents MacOS and Linux from working 🤔

**Comment by cswinter** [comment]
OK I believe 0.2.4 should be good now.

**Comment by ntoxeg** [comment]
@cswinter looks good but you will need to update HyperState as well to use that version (maybe relaxing the pin is a good idea too).

**Comment by ntoxeg** [comment]
All right, I thought something was wrong with HyperState’s version requirements but it worked now that I tried it again, thanks for the fix. @cswinter
