### ISSUE TITLE
v0.2.6 release

### ISSUE THREAD

**Issue by kaimast** [cswinter/pyron#7]
It would be great if you could you push a new release to pypi. Because of #6, I still need to build it from source everytime I want to install it.

**Comment by cswinter** [comment]
v0.2.5 was after the fix and is on PyPI, does it not fix the issue?

**Comment by kaimast** [comment]
Oh, I just realized I might have installed pyron not python-ron from pypi... Sorry for the confusion.

**Comment by cswinter** [comment]
Haha yeah I've done that multiple times. Let me know if you still run into any issues!
